### PR TITLE
Assemble and include the boot sector code when building mkfs.echfs

### PR DESCRIPTION
**Pull request by micahswitzer**
This PR replaces the byte array in `mkfs.echfs.c` with an object file that contains the assembled `boot.asm`. It also updates `boot.asm` to leave space for the reserved word and UUID. I can break out that change into a separate PR if you would like.

### CODE REVIEW

**Comment by Mintsuki** [comment]
This could be changed to use `objcopy` to create the object from the bootsector, instead of relying on `nasm`. In a similar fashion as https://github.com/limine-bootloader/limine/blob/7eb22e5c15d0b29ccf0126d3104fa996e416b868/Makefile#L17

**Comment by micahswitzer** [comment]
Okay, good idea. While I'm at it should I add a check to ensure the length of the boot sector code does not exceed 512 bytes? As it stands, exactly 512 bytes will be copied to the image. I could modify the behavior to ensure it never copies more than 512 bytes and prints a warning if it exceeds 512 bytes, e.g. `"The boot sector image is larger than 512 bytes, it will be truncated to fit"`.

**Comment by micahswitzer** [comment]
Now that I think about it, it would make more sense for the size to be checked at compile/build time since it is not a user-provided file. So I guess I could include a check in the recipe for `boot.bin` to assert that its size is either 512, or no larger than 512 after it is assembled?

**Comment by micahswitzer** [comment]
Updated branch here: https://github.com/echfs/echfs/compare/master...micahswitzer:bootsect-objcopy

Let me know if you like that better, and I'll close this PR and open a new one for that branch.

**Comment by Mintsuki** [comment]
LGTM, go ahead

**Pull request closed without merging**
